DROP TABLE IF EXISTS employee;

CREATE TABLE employee(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
salary DOUBLE NOT NULL,
address VARCHAR(100) NOT NULL,
gender enum('MALE', 'FEMALE') NOT NULL
);

DROP SEQUENCE IF EXISTS HIBERNATE_SEQUENCE;
CREATE SEQUENCE HIBERNATE_SEQUENCE START WITH 1 INCREMENT BY 1;